# Vectores y Valores propios de una matriz
En álgebra lineal podemos tener ecuaciones donde la incógnita es un vector

### $A*\bar{x}=\Lambda*\bar{x}$

$A:$ Matriz cuadrada NxN.

$\bar{x}:$ Es un vector columna cuyas componentes desconocemos.

Lo que esta ecuación nos pregunta es:
¿Existen vectores X tales que al multiplicarlos por la matriz A eso es equivalente a simplemente multiplicarlos por un número?
- R: Si tal vector existe y está asociado a un valor específico de Λ, entonces decimos que el vector X es un vector propio de la matriz A y Λ es su valor propio correspondiente.

Consideremos esto para el caso de una matriz 2 x 2, como la siguiente:

<img src="https://i.imgur.com/5AlP07v.png" alt="Alternative text"/>

Esto se traduce en el sistema de ecuaciones (haciendo el producto matriz por vector):

<img src="https://i.imgur.com/LVyLKYe.png" alt="Alternative text"/>


In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
a = np.array([[1,2],[1,0]])
print('matriz:\n',a)
# np.linalg.eig(A) lo que hace es calcular directamente los valores y vectores propios,
values, vector = np.linalg.eig(a)
print('values:\n', values, "\nvector:\n", vector)

matriz:
 [[1 2]
 [1 0]]
values:
 [ 2. -1.] 
vector:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


Es importante anotar que los vectores que entrega la función np.linalg.eig(A) son vectores columna de manera que los elementos de la primera columna de vectors corresponden con el primer valor de values y así sucesivamente.

<img src="https://i.imgur.com/7k3ZwIF.png" alt="Alternative text"/><br>
<img src="https://i.imgur.com/ZsJ3LAt.png" alt="Alternative text"/>

Puedes verificar que cada vector y su respectivo valor propio cumplen la ecuación original ejecutando cada parte así:

In [12]:
print("vector:\n",vector)
np.matmul(a, vector.T[1])


vector:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


array([ 0.70710678, -0.70710678])

In [18]:
print(values)
values[1]*vector.T[1]

[ 2. -1.]


array([ 0.70710678, -0.70710678])

Resulta en lo mismo: [ 0.70710678, -0.70710678]

Dado que: 
### $Ax = \Lambda x$

Uno de los hechos más importantes de obtener los vectores y valores propios de una matriz es poder **diagonalizarla**. En general se define que una matriz A es diagonalizable si es posible escribirla como el producto de:

<img src="https://i.imgur.com/yWyi48D.png" alt="Alternative text"/>

$D: $ Es una matriz diagonal

<img src="https://i.imgur.com/tRw3bAM.png" alt="Alternative text"/>

**Si una matriz es diagonalizable**, la matriz D se construye colocando sus valores propios en la diagonal y la matriz P se construye colocando en cada columna el vector propio

<img src="https://i.imgur.com/NNiVLu3.png" alt="Alternative text"/>

**La importancia** es que cuando aplicamos este cálculo de vectores y valores propios a una matriz de covarianza, <u>los vectores representan las direcciones a lo largo de las cuales percibimos la mayor cantidad de varianza de ese conjunto de datos</u>, donde la cantidad de varianza es proporcional al valor propio de cada vector propio.

**IMPORTANTE**
- Este procedimiento aplica para un conjunto de datos con N variables al que le corresponde una matriz de covarianza de tamaño NxN.
- Esta técnica es que para matrices de covarianza, sus vectores propios siempre son independientes unos de otros y esto es justamente lo que queremos en un proceso de reducción de variables, porque direcciones independientes implica que estos vectores representan nuevas variables cuya correlación es la más baja posible y así cada nueva variable es lo más representativa posible.

    En álgebra lineal se dice más precisamente que los vectores propios de una matriz de covarianza son ortogonales y esto quiere decir que el producto interno de cualquier par de estos vectores siempre da como resultado cero:
    
    <img src="https://i.imgur.com/IygBQDo.png" alt="Alternative text"/>

    Como consecuencia la matriz se denomina matriz ortogonal, y se sabe en matemáticas que la inversa de una matriz ortogonal es igual a la transpuesta, de manera que:

    <img src="https://i.imgur.com/20Iqk5V.png" alt="Alternative text"/>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=86e57948-5826-4e82-b8a9-8d73035014be' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>